tunnel: YOUR_TUNNEL_ID
credentials-file: C:\Users\YOUR_USER\.cloudflared\YOUR_TUNNEL_ID.json

ingress:
  - hostname: daedulus.dahuchsi.net
    service: http://localhost:3000
  - service: http_status:404