version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: daedulus
      POSTGRES_USER: daedulus_user
      POSTGRES_PASSWORD: your_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://daedulus_user:your_secure_password@postgres:5432/daedulus
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your_jwt_secret_here
      NODE_ENV: production
    volumes:
      - /L/PlexServ:/downloads
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:3001
      REACT_APP_WS_URL: ws://backend:3001
    ports:
      - "3000:3000"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - frontend
    environment:
      CLOUDFLARE_TUNNEL_TOKEN: ${CLOUDFLARE_